spring.application.name=AgoraLearn
# MongoDB
spring.mongodb.uri=mongodb://mongo:admin@mongo:27017/agora-mongo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/agora-postgres
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA/Hibernate (???? ???????????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ??????
server.port=8080
